# Alacritty
[env]
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/theme/catppuccin-macchiato.toml",
  "~/.config/alacritty/key-bindings.toml",
]

[window]
opacity = 0.9
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true
blur = true
padding = { x = 5, y = 5 }

[scrolling]
history = 10000
multiplier = 3

[bell]
duration = 0

[font]
size = 12.0
normal = { family = "MonoLisa Nerd Font", style = "Regular" }
bold = { family = "MonoLisa Nerd Font", style = "SemiBold" }
italic = { family = "MonoLisa Nerd Font", style = "Italic" }  # 'auto' is replaced with standard naming
bold_italic = { family = "MonoLisa Nerd Font", style = "Bold Italic" }

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
style =  { shape = "Beam", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Always" }
blink_interval = 500
